### PR TITLE
fixes static ref that keeps singletons in memory even when destroyed

### PR DESCRIPTION
**Pull request by LeanderSimonart**
This change is [Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/120)

### CODE REVIEW

**Review by Skeloson — APPROVED** [review]

**Review by LouisNillusFC — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/120)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @LeanderSimonart)

**Review by MaxDaniels — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/120)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @LeanderSimonart)

**Comment by MaxDaniels** [comment]
*[`Runtime/Singleton.cs` line 54 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/120#-O2cz6Ny4TEg_-d8ZkvC:-O2cz6Ny4TEg_-d8ZkvD:b-ruv5cw) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/152b503f91bec87d7de4971aa99e9ed23d81e7cf/Runtime/Singleton.cs#L54)):*
> ```Smalltalk
>         protected virtual void OnDestroy()
>         {
>             _instance = null;
> ```

If a second instance is created, in Awake() it will be destroyed and '_instance' will set to NULL.
Not sure but I think we should check the instance in OnDestroyed()



_Code snippet:_
```Smalltalk
if( _instance == this )
{
   _instance = null;
}
```

**Review by MaxDaniels — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/120)* status: all files reviewed, 1 unresolved discussion (waiting on @LeanderSimonart)

**Review by PetitT — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/120)* status: all files reviewed, 1 unresolved discussion (waiting on @LeanderSimonart)

**Review by LeanderSimonart — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/120)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @LouisNillusFC and @MaxDaniels)

___
*[`Runtime/Singleton.cs` line 54 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/120#-O2cz6Ny4TEg_-d8ZkvC:-O2dDq9vEi8q9_JTuNHR:b-896fix) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/152b503f91bec87d7de4971aa99e9ed23d81e7cf/Runtime/Singleton.cs#L54)):*
<details><summary><i>Previously, MaxDaniels wrote…</i></summary><blockquote>

If a second instance is created, in Awake() it will be destroyed and '_instance' will set to NULL.
Not sure but I think we should check the instance in OnDestroyed()
</blockquote></details>

Done.

**Review by MaxDaniels — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/120)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @LeanderSimonart)

**Review by lucas-baran — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/120)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @LeanderSimonart)

**Pull request merged**
