### PR TITLE
Add default value to param in Optional.TryGetValueOrDefault

### PR DESCRIPTION
**Pull request by rascar-capac**
This change is [Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/108)

### CODE REVIEW

**Review by LeanderSimonart — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/108#-:-NvBehoq5DGs7DvQs8JQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rascar-capac)

**Review by LeanderSimonart — APPROVED** [review]
might need to update version number?

> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/108#-:-NvBejeMBGbDMlQiUNBi:bv7y480)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rascar-capac)

**Review by LouisNillusFC — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/108)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rascar-capac)

**Review by Skeloson — APPROVED** [review]

**Comment by Skeloson** [comment]
Dont forget to update the package version

**Review by fishingcactus-nathan-istace — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/108)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rascar-capac)

**Review by lucas-baran — APPROVED** [review]
Don't forget to update the version again xD

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/108#-:-NvC_3Sk94-g4S6_ihNu:brd8n6b)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rascar-capac)

**Pull request merged**
