### PR TITLE
publish config and ICollection.Contains implementations

### PR DESCRIPTION
**Pull request by lucas-baran**
merge after #108 

- add publish config in package.json
- `SerializableDictionary.KeyCollection.Contains` and `SerializableDictionary.ValueCollection.Contains` are now public instead of explicitly implementing `ICollection.Contains`

- - -
This change is [Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/109)

### CODE REVIEW

**Review by Skeloson — APPROVED** [review]

**Review by TheEmidee — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/109#-:-NvH-guyApAzNKVY9PsE:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @fishingcactus-nathan-istace, @LeanderSimonart, @LouisNillusFC, @MaxDaniels, @PetitT, @rascar-capac, and @ThibNach)

**Review by fishingcactus-nathan-istace — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/109)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @LeanderSimonart, @LouisNillusFC, @MaxDaniels, @PetitT, @rascar-capac, and @ThibNach)

**Review by rascar-capac — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/109)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @LeanderSimonart, @LouisNillusFC, @MaxDaniels, @PetitT, and @ThibNach)

**Review by LeanderSimonart — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/109)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @LouisNillusFC, @MaxDaniels, @PetitT, and @ThibNach)

**Review by LouisNillusFC — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/109)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
