### PR TITLE
Feature/optional improvements

### PR DESCRIPTION
**Pull request by lucas-baran**
### Added
- Add Optional::TryGetValueOrDefault function
- Add .editorconfig for VS users

- - -
This change is [Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/105)

### CODE REVIEW

**Review by LouisNillusFC — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/105)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @fishingcactus-nathan-istace, @MaxDaniels, @PetitT, @rascar-capac, @Skeloson, @TheEmidee, and @ThibNach)

**Review by ThibNach — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/105#-:-NnOAmer6MuiNlaKxAfS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @fishingcactus-nathan-istace, @MaxDaniels, @PetitT, @rascar-capac, @Skeloson, and @TheEmidee)

**Review by PetitT — APPROVED** [review]

**Review by rascar-capac — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/105)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @fishingcactus-nathan-istace, @MaxDaniels, @Skeloson, and @TheEmidee)

**Review by Skeloson — APPROVED** [review]

**Review by TheEmidee — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/105)* status: all files reviewed, 1 unresolved discussion (waiting on @fishingcactus-nathan-istace, @lucas-baran, and @MaxDaniels)

*[a discussion](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/105#-NnOWp0T6BsSJ7EA41Nx:-NnOWp0T6BsSJ7EA41Ny:b-ghe4r1) (no related file):*
Can someone tell me why we need this class? Because in C# we can make non-nullable types optional by suffixing the type with `?`

Ex: `int? i;`

___

**Review by rascar-capac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/105)* status: all files reviewed, 1 unresolved discussion (waiting on @fishingcactus-nathan-istace, @MaxDaniels, and @TheEmidee)

*[a discussion](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/105#-NnOWp0T6BsSJ7EA41Nx:-NnOdjVeCo-87dYEpDvi:b-gaqk7k) (no related file):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

Can someone tell me why we need this class? Because in C# we can make non-nullable types optional by suffixing the type with `?`

Ex: `int? i;`
</blockquote></details>

This comes along with a custom property drawer, in the inspector it adds a checkbox in front of it. I don't know how it would behave if it was made for `Nullable`, maybe it could be worth it to try

___

**Review by TheEmidee — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/105#-:-NnOjTEm9KYaGB7_WFtP:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @fishingcactus-nathan-istace, @MaxDaniels, and @rascar-capac)

*[a discussion](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/105#-NnOWp0T6BsSJ7EA41Nx:-NnOjORf7683PcHC_434:b807puj) (no related file):*
<details><summary><i>Previously, rascar-capac (Théo Constant) wrote…</i></summary><blockquote>

This comes along with a custom property drawer, in the inspector it adds a checkbox in front of it. I don't know how it would behave if it was made for `Nullable`, maybe it could be worth it to try
</blockquote></details>

ah yes OK I did not get this has a property drawer

___

**Pull request merged**
