### PR TITLE
Add attribute to hide types in create asset menu

### PR DESCRIPTION
**Pull request by lucas-baran**
### Added
- Add `HideInCreateAssetDropdownAttribute`: scriptable object classes that define this attribute are hidden in the create asset dropdown
### Fixed
- Fix an null ref exception inside `MathematicsVectorContextMenu` that prevented context menus from being displayed on specific properties on certain components (eg: rotation property on `Transform`)

This change is [Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/117)

### CODE REVIEW

**Review by MaxDaniels — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/117)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lucas-baran)

**Review by LeanderSimonart — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/117#-:-Ny_aZ9YCPbLYHuOVa3y:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lucas-baran)

**Review by rascar-capac — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/117)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lucas-baran)

**Review by PetitT — APPROVED** [review]

**Review by TheEmidee — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/117#-:-NytpcCg9QL4eKvrU2sI:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lucas-baran)

**Review by Skeloson — APPROVED** [review]

**Review by rascar-capac — APPROVED** [review]
You can now add a description to the readme for your new attribute <3

> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/117#-:-NytzziYEFe06i6smz-A:b-faje9b)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lucas-baran)

**Review by fishingcactus-nathan-istace — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/117)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lucas-baran)

**Review by TheEmidee — APPROVED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/117)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lucas-baran)

**Comment by lucas-baran** [comment]
I updated the version number, and fixed the compilation errors and merge conflicts caused by v2.0.0, as well as updated the README

**Review by TheEmidee — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/117#-:-Nz2_T1d7jyZAKTDdaWm:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lucas-baran)

**Pull request merged**
