### PR TITLE
Fix/add unity mathematics dependency

### PR DESCRIPTION
**Pull request by lucas-baran**
This change is [Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116)

### CODE REVIEW

**Comment by fishingcactus-nathan-istace** [comment]
*[`package.json` line 8 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116#-NxCWW0GBUTQIZwrdNXr:-NxCWW0GBUTQIZwrdNXs:b3aqplq) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/f20d3b8733bf53eab8cc1da97b80bffa350d25cd/package.json#L8)):*
> ```JSON
>   "unity": "2020.3",
>   "unityRelease": "18f1",
>     "author": {
> ```

Weird indent here, "author" should be at the same level as "unityRelease", right?

**Review by fishingcactus-nathan-istace — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lucas-baran)

**Review by Snibaw — APPROVED** [review]

**Review by TheEmidee — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116)* status: all files reviewed, 1 unresolved discussion (waiting on @lucas-baran)

___
*[`package.json` line 14 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116#-NxCXoVe5G4f0tQHVRQV:-NxCXoVe5G4f0tQHVRQW:b-pm4xe) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/f20d3b8733bf53eab8cc1da97b80bffa350d25cd/package.json#L14)):*
> ```JSON
>     },
>   "dependencies": {
>     "com.unity.mathematics": "1.2.6"
> ```

is this dependency required for code that's in this package?

**Review by TheEmidee — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116)* status: all files reviewed, 1 unresolved discussion (waiting on @lucas-baran)

**Review by LouisNillusFC — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116)* status: all files reviewed, 1 unresolved discussion (waiting on @lucas-baran)

**Review by TheEmidee — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116)* status: all files reviewed, 1 unresolved discussion (waiting on @lucas-baran)

**Review by lucas-baran — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116)* status: all files reviewed, 1 unresolved discussion (waiting on @lucas-baran)

___
*[`package.json` line 8 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116#-NxCWW0GBUTQIZwrdNXr:-NxCk_8s6jilDRX2MKb1:b4849hh) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/f20d3b8733bf53eab8cc1da97b80bffa350d25cd/package.json#L8)):*
<details><summary><i>Previously, fishingcactus-nathan-istace (NathanIstace) wrote…</i></summary><blockquote>

Weird indent here, "author" should be at the same level as "unityRelease", right?
</blockquote></details>

Done.
Don't know why it got changed
___
*[`package.json` line 14 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116#-NxCXoVe5G4f0tQHVRQV:-NxCk4QxE0JJQndsiGzg:bvhilj5) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/f20d3b8733bf53eab8cc1da97b80bffa350d25cd/package.json#L14)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

is this dependency required for code that's in this package?
</blockquote></details>

Yes, it's required for the recent changes from the last PR, Romain got the compilation error this morning while updating the version of the package for the settings package. Honestly the mathematics package is so common there's no reason to not have it in a any project.
I think it's possible to define scripting symbols from the assembly when a package exists and check with conditional directives in code, that way the dependency wouldn't be needed and the corresponding code would only be compiled if the project that uses the package has the dependency package imported.

**Review by Skeloson — APPROVED** [review]

**Review by MaxDaniels — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116)* status: all files reviewed, 1 unresolved discussion (waiting on @TheEmidee)

**Review by rascar-capac — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116)* status: all files reviewed, 1 unresolved discussion (waiting on @TheEmidee)

___
*[`package.json` line 14 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116#-NxCXoVe5G4f0tQHVRQV:-NxCqbNa2sNLalx27Uxd:b-3d6er6) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/f20d3b8733bf53eab8cc1da97b80bffa350d25cd/package.json#L14)):*
<details><summary><i>Previously, lucas-baran (Lucas Baran) wrote…</i></summary><blockquote>

Yes, it's required for the recent changes from the last PR, Romain got the compilation error this morning while updating the version of the package for the settings package. Honestly the mathematics package is so common there's no reason to not have it in a any project.
I think it's possible to define scripting symbols from the assembly when a package exists and check with conditional directives in code, that way the dependency wouldn't be needed and the corresponding code would only be compiled if the project that uses the package has the dependency package imported.
</blockquote></details>

You should write `1.x` instead in order to support any new compatible update. I hope that we can trust Unity to follow that convention.

**Review by TheEmidee — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lucas-baran)

___
*[`package.json` line 14 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116#-NxCXoVe5G4f0tQHVRQV:-NxD8KP_5MjwZWjJwH4W:bxt43pl) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/f20d3b8733bf53eab8cc1da97b80bffa350d25cd/package.json#L14)):*
<details><summary><i>Previously, rascar-capac (Théo Constant) wrote…</i></summary><blockquote>

You should write `1.x` instead in order to support any new compatible update. I hope that we can trust Unity to follow that convention.
</blockquote></details>

if we have code that needs it, no problem to depend on it

**Review by TheEmidee — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116#-:-NxD8P-4EjkFEkPCXySj:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lucas-baran)

**Review by lucas-baran — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @fishingcactus-nathan-istace, @LouisNillusFC, @MaxDaniels, @rascar-capac, and @TheEmidee)

___
*[`package.json` line 14 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116#-NxCXoVe5G4f0tQHVRQV:-NxDC08C7Vjd97e4MriM:bttpl6j) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/f20d3b8733bf53eab8cc1da97b80bffa350d25cd/package.json#L14)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

if we have code that needs it, no problem to depend on it
</blockquote></details>

In the end I updated it to use a symbol because it's just added functionality (the package doesn't need it to function in any way) so makes more sense to not require a dependency at all
___
*[`Editor/ContextMenus/PropertyContextMenus/MathematicsVectorContextMenu.cs` line 1 at r3](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116#-NxDCXkQ9WdEhr6Jaccz:-NxDCXkQ9WdEhr6Jacd-:b-g62uk8) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/63de4ef7d9a6de8acdf5b363570b1e53bc98a075/Editor/ContextMenus/PropertyContextMenus/MathematicsVectorContextMenu.cs#L1)):*
> ```Smalltalk
> #if MATHEMATICS_AVAILABLE
> ```

this is defined in the editor assembly if any version of mathematics is available
___
*[`Runtime/FishingCactus.CommonCode.Runtime.asmdef` line 5 at r3](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116#-NxDCPY07heI4aLf9uJQ:-NxDCPY07heI4aLf9uJR:b-rzt6t8) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/2533bb1b9ce25a6e5359f1eee588ed91114f530b/Runtime/FishingCactus.CommonCode.Runtime.asmdef#L5)):*
> ```
>     "rootNamespace": "",
>     "references": [
>         "GUID:d8b63aba1907145bea998dd612889d6b"
> ```

this is the mathematics reference I removed because it is not used inside the runtime assembly

**Review by fishingcactus-nathan-istace — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 5 of 7 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @LouisNillusFC, @MaxDaniels, @rascar-capac, @Skeloson, @Snibaw, and @TheEmidee)

**Review by rascar-capac — APPROVED** [review]
> Reviewed 5 of 7 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @LouisNillusFC, @MaxDaniels, @Skeloson, @Snibaw, and @TheEmidee)

___
*[`package.json` line 14 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116#-NxCXoVe5G4f0tQHVRQV:-NxDPXUy-YOvWqukJ7Ll:b8d5b2x) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/f20d3b8733bf53eab8cc1da97b80bffa350d25cd/package.json#L14)):*
<details><summary><i>Previously, lucas-baran (Lucas Baran) wrote…</i></summary><blockquote>

In the end I updated it to use a symbol because it's just added functionality (the package doesn't need it to function in any way) so makes more sense to not require a dependency at all
</blockquote></details>

You can remove `resolutionStrategy`, after some reading it appears that we should put it in our projects' manifest but not in the packages. This is only used to let UPM know what to do when some indirect dependencies are conflicting.

**Review by TheEmidee — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @LouisNillusFC, @MaxDaniels, @Skeloson, and @Snibaw)

**Review by lucas-baran — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @fishingcactus-nathan-istace, @LouisNillusFC, @MaxDaniels, @rascar-capac, @Skeloson, and @Snibaw)

___
*[`package.json` line 14 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116#-NxCXoVe5G4f0tQHVRQV:-NxGz7ojDvtJR5XYdMf-:b-896fix) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/f20d3b8733bf53eab8cc1da97b80bffa350d25cd/package.json#L14)):*
<details><summary><i>Previously, rascar-capac (Théo Constant) wrote…</i></summary><blockquote>

You can remove `resolutionStrategy`, after some reading it appears that we should put it in our projects' manifest but not in the packages. This is only used to let UPM know what to do when some indirect dependencies are conflicting.
</blockquote></details>

Done.

**Review by Snibaw — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @LouisNillusFC, @MaxDaniels, and @Skeloson)

**Review by fishingcactus-nathan-istace — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @LouisNillusFC, @MaxDaniels, and @Skeloson)

**Review by LeanderSimonart — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @LouisNillusFC, @MaxDaniels, and @Skeloson)

**Review by TheEmidee — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116#-:-NxIB4Kv9rkkhxlwMjxD:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @LouisNillusFC, @MaxDaniels, and @Skeloson)

**Review by PetitT — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/116)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @LouisNillusFC, @MaxDaniels, and @Skeloson)

**Pull request merged**
