### PR TITLE
EnumFlagsAttribute + drawer added.

### PR DESCRIPTION
**Pull request by MaxDaniels**
Base code from Exiin.

---
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/unitycommoncode/57)

### CODE REVIEW

**Review by rams3s — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fishingcactus/unitycommoncode/57)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by TheEmidee — APPROVED** [review]
There already exists a Flags attribute. you need to define another one, if you want to have a custom drawer?

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fishingcactus/unitycommoncode/57#-:-L_C0kln3CgPVlL4Ioq-:b-kstcwk)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by NuclearCookie — APPROVED** [review]
Yes.
You specify [Flags] on the enum type definition,
You use [EnumFlags] on the instantiated, serialized type to use it without custom editor.

```
[Flags]
public enum MyEnum
{
    One 1 << 0,
    Two 1 << 1
}

[SerializeField][EnumFlags]
private MyEnum myEnum;
```

> *[Reviewable](https://reviewable.io/reviews/fishingcactus/unitycommoncode/57#-:-L_CD3MN7St6g4zFQ2g9:bs3udlz)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by rams3s — APPROVED** [review]

**Review by TheEmidee — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/fishingcactus/unitycommoncode/57#-:-L_DC7bAASXYZ35eJI5S:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by TheEmidee — APPROVED** [review]
for some readon I thought that EnumFlags would replace the Flags :|

> *[Reviewable](https://reviewable.io/reviews/fishingcactus/unitycommoncode/57#-:-L_DC8zq4YhmPOsKoPYH:b-90dx8l)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
