### PR TITLE
Feature/serializable interface

### PR DESCRIPTION
**Pull request by lucas-baran**
### Added
- Add `SerializableInterface` struct: used to reference objects that implement a specific interface
- Add `CustomObjectField`: used to draw customized object field with more functionality than `EditorGUILayout.ObjectField`
### Updated
- Moved `HideInCreateAssetDropdownAttribute` inside `FishingCactus.CommonCode` namespace

- - -
This change is [Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/118)

### CODE REVIEW

**Review by fishingcactus-nathan-istace — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/118)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lucas-baran)

**Review by TheEmidee — APPROVED** [review]
> Reviewed 5 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/118)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lucas-baran)

**Review by TheEmidee — APPROVED** [review]
> Reviewed 5 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/118)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lucas-baran)

**Review by TheEmidee — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/118#-:-NzUR59F3xNGr1FFCc5K:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lucas-baran)

**Review by rascar-capac — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/118)* status: all files reviewed, 1 unresolved discussion (waiting on @lucas-baran)

___
*[`README.md` line 21 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/118#-NzbW2Gz4YFesq5l_W0w:-NzbW2Gz4YFesq5l_W0x:blvbpl2) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/93447928a7af5d110377e8eae499e519ef3859c0/README.md#L21)):*
> ```Markdown
> | `NetworkStatusChecker`                 | X       |       |               |                                                                      |
> | `Optional`                             |         |       | X             | Wrapper to create optional values                                    |
> | `SerializableInterface`                |         |       | X             | Wrapper reference objects that implements a specific interface       |
> ```

I don't understand your description xD did you mean "wrapper to reference objects that implement a specific interface"?

**Review by PetitT — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/118)* status: all files reviewed, 1 unresolved discussion (waiting on @lucas-baran)

**Review by lucas-baran — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/118)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @fishingcactus-nathan-istace, @rascar-capac, and @TheEmidee)

___
*[`README.md` line 21 at r1](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/118#-NzbW2Gz4YFesq5l_W0w:-NzgREWcBhsBSlAySWVw:b-4j0x7l) ([raw file](https://github.com/FishingCactus/UnityCommonCode/blob/93447928a7af5d110377e8eae499e519ef3859c0/README.md#L21)):*
<details><summary><i>Previously, rascar-capac (Théo Constant) wrote…</i></summary><blockquote>

I don't understand your description xD did you mean "wrapper to reference objects that implement a specific interface"?
</blockquote></details>

Indeed, that made no sense

**Review by rascar-capac — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/118)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lucas-baran)

**Review by MaxDaniels — APPROVED** [review]
> Reviewed 8 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/118)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lucas-baran)

**Review by LouisNillusFC — APPROVED** [review]
> Reviewed 8 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/118)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lucas-baran)

**Review by fishingcactus-nathan-istace — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FishingCactus/UnityCommonCode/118)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
